import React from 'react';

export default () => {
  return (
    <div style={{ gridArea: 'body' }}>
      <div id="section1" style={{ padding: '2rem' }}>
        <a href="#section2" style={{ fontSize: '3rem' }}>
          To section 2
        </a>
        {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis convallis ipsum sit amet porttitor. Curabitur dignissim sem quis aliquet pulvinar. Aliquam facilisis velit sed elit condimentum, vitae rhoncus lectus imperdiet. Fusce massa ipsum, ultricies dapibus est vel, scelerisque suscipit nulla. Mauris feugiat venenatis nunc, sit amet scelerisque ligula dictum vitae. Mauris nunc ex, dignissim eu laoreet ac, fringilla ac sapien. Nullam ornare facilisis efficitur. Nam volutpat auctor nibh, non mollis sapien hendrerit a. Quisque ornare ex vitae velit tempus sodales. Mauris sagittis risus dapibus, commodo urna ac, ornare mi. Donec ullamcorper augue sit amet ligula scelerisque, et finibus enim tincidunt. Integer vel lacus pretium, aliquam purus eget, viverra sapien. Pellentesque in est at eros dapibus laoreet non a odio. Aliquam risus ipsum, tincidunt imperdiet quam a, fringilla gravida erat. Pellentesque id metus vitae urna rhoncus egestas.

    Etiam vel sollicitudin orci, sit amet venenatis orci. Ut scelerisque risus sit amet lacus gravida, at dignissim erat dictum. Quisque hendrerit nunc vitae mi volutpat, eu aliquam leo fermentum. Etiam tristique metus sed risus suscipit, a tempor turpis pharetra. Nam id tellus non quam euismod ornare a sed ligula. Duis neque diam, varius non finibus non, gravida a risus. In eu leo pharetra, viverra mi non, tincidunt massa. Maecenas facilisis fermentum diam, nec bibendum massa maximus venenatis. Aliquam euismod egestas vestibulum. Mauris eleifend ornare erat non sagittis. Nullam iaculis pellentesque dolor, mattis maximus dui sollicitudin at. Nunc at elit sit amet erat laoreet convallis. Fusce id dapibus est.
    
    Nulla ullamcorper eros sit amet nunc ornare, sed molestie nulla ultrices. Cras auctor nisi at velit laoreet, nec viverra risus lacinia. Ut eros leo, hendrerit condimentum nisi a, rutrum vulputate libero. Ut feugiat diam vitae neque sollicitudin dignissim. Vestibulum in blandit est. Donec rutrum aliquam tempor. Aenean gravida, felis a sodales sagittis, sem tellus aliquam odio, eget fermentum enim nisi et nulla. Curabitur tortor tellus, rutrum sollicitudin massa quis, faucibus elementum sapien. Donec accumsan, risus non tempus consequat, massa odio volutpat tellus, eu maximus metus justo id massa. In tempor orci urna. Donec feugiat dictum cursus. Quisque sollicitudin ullamcorper quam, vel iaculis mauris interdum non. Vivamus finibus congue purus, sed tempor eros dictum vitae. Vestibulum mollis tincidunt arcu ac lacinia. Nunc dui quam, viverra in ipsum in, convallis venenatis nisl. Cras vestibulum semper purus, eget commodo dui luctus a.
    
    In suscipit urna vitae eros ullamcorper, et faucibus augue dictum. Mauris ultrices dignissim enim a gravida. Aenean quis tortor commodo felis finibus bibendum. Proin in erat sagittis, euismod sem eget, condimentum lorem. Ut lacinia nunc id lorem dictum, quis condimentum turpis mattis. Ut ut viverra nisl. Morbi dolor magna, consequat ac posuere non, dignissim vel diam. Nunc sit amet felis eget massa fringilla vehicula. Vivamus congue egestas ornare. Aliquam vitae arcu erat. Fusce sed viverra justo, ac tincidunt lacus. Integer porta felis a iaculis vehicula. Vivamus elementum, justo at molestie rhoncus, metus orci elementum risus, eu blandit augue purus et lorem. Mauris nec lectus tortor. Vivamus tempus ultricies ante, ac semper neque iaculis a.
    
    Morbi ornare mollis sagittis. Pellentesque vel elit nec ante fringilla lobortis ac semper nisl. Praesent at ipsum eleifend, euismod lacus malesuada, iaculis elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec lorem nulla, rhoncus sed mollis non, consectetur sit amet sapien. Sed id mauris id ipsum pulvinar euismod. Ut laoreet lectus a nisi lobortis porta. Vivamus molestie odio sed pellentesque scelerisque. Proin lacus nisi, mollis sed erat id, finibus varius enim. Duis metus orci, malesuada ut ipsum ac, elementum placerat risus. Morbi sagittis diam in purus feugiat, vel venenatis felis viverra. Aenean magna nulla, gravida tempor ex eget, fringilla facilisis quam. Cras suscipit eleifend justo ac hendrerit.
    
    Ut vel congue lacus, in hendrerit leo. Sed et dolor consequat sem commodo dapibus. Vestibulum sodales varius metus, in porta sapien convallis ut. Mauris luctus ultricies lacus, sed tempor velit. Nunc at diam mattis, ullamcorper eros eu, maximus leo. Duis consectetur, ligula eget cursus consequat, erat quam interdum augue, nec molestie neque arcu nec ante. Nulla posuere lobortis ex, a placerat lacus tincidunt quis. Suspendisse augue sem, pharetra eget mi vitae, pretium elementum mauris.
    
    Pellentesque at cursus tellus. Quisque id porta dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque at eros auctor, pretium est sit amet, elementum felis. Quisque tristique, nunc non suscipit dapibus, erat augue porttitor arcu, id elementum sem ante a nisl. Suspendisse eget nisl in arcu ultricies rutrum. Proin finibus, magna at rhoncus pretium, est ante tempor nunc, at finibus augue nulla sodales sem. Cras efficitur pellentesque faucibus. Aenean ultrices arcu tortor, nec accumsan diam dignissim in. Integer eu facilisis metus, non sodales eros. Aenean at arcu eu eros sagittis dapibus in vel ligula. Phasellus fermentum metus magna. Nam pulvinar dignissim libero, non malesuada metus sollicitudin vel. Aenean ornare turpis a eros hendrerit, vitae pulvinar massa mollis.
    
    Sed mollis arcu sed ex ornare hendrerit. Sed porta, eros vitae malesuada dictum, sapien lacus volutpat tortor, ut commodo tellus risus ac leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus tellus vel tristique posuere. Cras suscipit feugiat felis quis tristique. Integer in lobortis purus, a volutpat nulla. Etiam cursus rhoncus felis at placerat. Aenean lectus mi, vulputate eget facilisis molestie, molestie id augue. Nunc lacus ligula, ultricies vitae tincidunt non, tincidunt sed turpis. Phasellus pharetra id ante rhoncus faucibus. Cras rutrum quam lobortis nisl congue, sed vehicula turpis feugiat. Morbi vitae sagittis turpis. Nam mattis, tortor vel pharetra gravida, massa augue dapibus mi, eu aliquam mi libero euismod lectus. Sed condimentum mi ut ex dignissim porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras enim libero, lobortis ac purus semper, laoreet scelerisque odio.
    
    Etiam mattis dolor dui, id tempus eros ultricies vel. Cras ut felis sodales, tincidunt elit ut, dictum lorem. Sed quis augue nec massa pulvinar congue ac id tortor. Praesent consectetur at eros ac varius. Quisque congue diam ac nibh aliquam rhoncus. Sed eget ligula ex. Morbi eu purus feugiat, interdum libero condimentum, accumsan ligula. In rutrum magna justo, a accumsan nibh pulvinar nec. In quam ligula, vulputate molestie odio eget, efficitur laoreet ante. Aenean vel ornare ligula, vitae egestas dolor. Aliquam in massa vitae urna hendrerit venenatis. Nulla cursus molestie elementum. Vestibulum consequat sed sapien nec mattis. Nulla porta feugiat libero, at volutpat lacus lacinia et.
    
    Aenean massa justo, suscipit nec odio non, dignissim iaculis velit. Cras ornare luctus tortor ut convallis. Vestibulum porta convallis urna, sed luctus justo auctor vel. Donec quis orci ut arcu semper aliquet. Fusce viverra purus sed malesuada imperdiet. Donec id nulla ipsum. Curabitur condimentum efficitur eros ac eleifend. Vestibulum bibendum euismod urna. Morbi imperdiet eu magna dignissim posuere. Nullam eget nulla sodales, sagittis leo sit amet, ornare felis. Sed sit amet eleifend velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus auctor facilisis enim, pulvinar lacinia leo blandit sed. Nulla non est sed lacus aliquet posuere vel nec quam.
    
    Sed iaculis aliquet pharetra. Nulla eget lectus at dolor fermentum placerat. Etiam at feugiat ipsum. Duis aliquet ligula nec luctus ornare. Praesent sagittis arcu et risus gravida sagittis. Nulla ex sem, convallis eget luctus sed, tempus eget sapien. Sed vitae laoreet metus. Cras quis lobortis ipsum, sit amet bibendum erat. Nulla fermentum consequat enim eu congue. Suspendisse at ultricies nunc, at condimentum neque. Sed vulputate id velit sit amet commodo. Suspendisse potenti.
    
    In tempor ante ac velit vulputate consequat. Donec a nunc gravida, lacinia erat eu, venenatis ipsum. In finibus mauris in quam tristique, in ornare leo molestie. Etiam in tortor egestas, varius ipsum vel, consectetur nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer fermentum justo id elit pellentesque vestibulum. Aenean auctor venenatis neque, at pellentesque neque convallis convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et odio posuere, vehicula enim a, euismod elit. Ut luctus id turpis in pellentesque.
    
    Etiam nec viverra leo. Integer vestibulum pulvinar tempor. Vestibulum consequat orci odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc ullamcorper eu nisl laoreet luctus. Nunc aliquam ante eget dolor viverra, sed eleifend felis tristique. Suspendisse convallis leo sit amet massa luctus, et tempus mi sagittis. Aliquam eget augue a turpis imperdiet mattis id vel metus.
    
    Cras fermentum, nisl lacinia rhoncus suscipit, magna nibh vulputate lorem, vel vehicula orci lacus quis nisi. Aliquam erat volutpat. Sed id urna ac velit commodo commodo ut ut tellus. Nullam a consectetur nulla. Vestibulum a dui tellus. Duis ultrices elementum enim sed feugiat. Vivamus justo libero, luctus ut erat eget, dictum pulvinar odio. Nulla interdum enim turpis. Aliquam porta rhoncus libero, nec imperdiet felis porta id. Curabitur congue ultrices lacinia.
    
    Etiam non accumsan ex. Ut commodo elit eget convallis finibus. Phasellus gravida metus vitae risus euismod accumsan. Praesent nunc tellus, sodales eu vulputate vitae, consectetur a leo. Aenean ullamcorper, nunc non posuere porttitor, risus lorem feugiat neque, in posuere turpis nulla vel lorem. Duis eget laoreet nisi, vitae egestas odio. Nam dignissim, lectus ut blandit dapibus, tortor erat aliquam nisi, sed viverra nulla lectus rutrum leo. Pellentesque tincidunt rhoncus ipsum id feugiat.`}
      </div>
      <div id="section2" style={{ padding: '4rem' }}>
        <a href="#section1" style={{ fontSize: '3rem' }}>
          To section 1
        </a>
        {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla lobortis convallis ipsum sit amet porttitor. Curabitur dignissim sem quis aliquet pulvinar. Aliquam facilisis velit sed elit condimentum, vitae rhoncus lectus imperdiet. Fusce massa ipsum, ultricies dapibus est vel, scelerisque suscipit nulla. Mauris feugiat venenatis nunc, sit amet scelerisque ligula dictum vitae. Mauris nunc ex, dignissim eu laoreet ac, fringilla ac sapien. Nullam ornare facilisis efficitur. Nam volutpat auctor nibh, non mollis sapien hendrerit a. Quisque ornare ex vitae velit tempus sodales. Mauris sagittis risus dapibus, commodo urna ac, ornare mi. Donec ullamcorper augue sit amet ligula scelerisque, et finibus enim tincidunt. Integer vel lacus pretium, aliquam purus eget, viverra sapien. Pellentesque in est at eros dapibus laoreet non a odio. Aliquam risus ipsum, tincidunt imperdiet quam a, fringilla gravida erat. Pellentesque id metus vitae urna rhoncus egestas.

    Etiam vel sollicitudin orci, sit amet venenatis orci. Ut scelerisque risus sit amet lacus gravida, at dignissim erat dictum. Quisque hendrerit nunc vitae mi volutpat, eu aliquam leo fermentum. Etiam tristique metus sed risus suscipit, a tempor turpis pharetra. Nam id tellus non quam euismod ornare a sed ligula. Duis neque diam, varius non finibus non, gravida a risus. In eu leo pharetra, viverra mi non, tincidunt massa. Maecenas facilisis fermentum diam, nec bibendum massa maximus venenatis. Aliquam euismod egestas vestibulum. Mauris eleifend ornare erat non sagittis. Nullam iaculis pellentesque dolor, mattis maximus dui sollicitudin at. Nunc at elit sit amet erat laoreet convallis. Fusce id dapibus est.
    
    Nulla ullamcorper eros sit amet nunc ornare, sed molestie nulla ultrices. Cras auctor nisi at velit laoreet, nec viverra risus lacinia. Ut eros leo, hendrerit condimentum nisi a, rutrum vulputate libero. Ut feugiat diam vitae neque sollicitudin dignissim. Vestibulum in blandit est. Donec rutrum aliquam tempor. Aenean gravida, felis a sodales sagittis, sem tellus aliquam odio, eget fermentum enim nisi et nulla. Curabitur tortor tellus, rutrum sollicitudin massa quis, faucibus elementum sapien. Donec accumsan, risus non tempus consequat, massa odio volutpat tellus, eu maximus metus justo id massa. In tempor orci urna. Donec feugiat dictum cursus. Quisque sollicitudin ullamcorper quam, vel iaculis mauris interdum non. Vivamus finibus congue purus, sed tempor eros dictum vitae. Vestibulum mollis tincidunt arcu ac lacinia. Nunc dui quam, viverra in ipsum in, convallis venenatis nisl. Cras vestibulum semper purus, eget commodo dui luctus a.
    
    In suscipit urna vitae eros ullamcorper, et faucibus augue dictum. Mauris ultrices dignissim enim a gravida. Aenean quis tortor commodo felis finibus bibendum. Proin in erat sagittis, euismod sem eget, condimentum lorem. Ut lacinia nunc id lorem dictum, quis condimentum turpis mattis. Ut ut viverra nisl. Morbi dolor magna, consequat ac posuere non, dignissim vel diam. Nunc sit amet felis eget massa fringilla vehicula. Vivamus congue egestas ornare. Aliquam vitae arcu erat. Fusce sed viverra justo, ac tincidunt lacus. Integer porta felis a iaculis vehicula. Vivamus elementum, justo at molestie rhoncus, metus orci elementum risus, eu blandit augue purus et lorem. Mauris nec lectus tortor. Vivamus tempus ultricies ante, ac semper neque iaculis a.
    
    Morbi ornare mollis sagittis. Pellentesque vel elit nec ante fringilla lobortis ac semper nisl. Praesent at ipsum eleifend, euismod lacus malesuada, iaculis elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec lorem nulla, rhoncus sed mollis non, consectetur sit amet sapien. Sed id mauris id ipsum pulvinar euismod. Ut laoreet lectus a nisi lobortis porta. Vivamus molestie odio sed pellentesque scelerisque. Proin lacus nisi, mollis sed erat id, finibus varius enim. Duis metus orci, malesuada ut ipsum ac, elementum placerat risus. Morbi sagittis diam in purus feugiat, vel venenatis felis viverra. Aenean magna nulla, gravida tempor ex eget, fringilla facilisis quam. Cras suscipit eleifend justo ac hendrerit.
    
    Ut vel congue lacus, in hendrerit leo. Sed et dolor consequat sem commodo dapibus. Vestibulum sodales varius metus, in porta sapien convallis ut. Mauris luctus ultricies lacus, sed tempor velit. Nunc at diam mattis, ullamcorper eros eu, maximus leo. Duis consectetur, ligula eget cursus consequat, erat quam interdum augue, nec molestie neque arcu nec ante. Nulla posuere lobortis ex, a placerat lacus tincidunt quis. Suspendisse augue sem, pharetra eget mi vitae, pretium elementum mauris.
    
    Pellentesque at cursus tellus. Quisque id porta dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque at eros auctor, pretium est sit amet, elementum felis. Quisque tristique, nunc non suscipit dapibus, erat augue porttitor arcu, id elementum sem ante a nisl. Suspendisse eget nisl in arcu ultricies rutrum. Proin finibus, magna at rhoncus pretium, est ante tempor nunc, at finibus augue nulla sodales sem. Cras efficitur pellentesque faucibus. Aenean ultrices arcu tortor, nec accumsan diam dignissim in. Integer eu facilisis metus, non sodales eros. Aenean at arcu eu eros sagittis dapibus in vel ligula. Phasellus fermentum metus magna. Nam pulvinar dignissim libero, non malesuada metus sollicitudin vel. Aenean ornare turpis a eros hendrerit, vitae pulvinar massa mollis.
    
    Sed mollis arcu sed ex ornare hendrerit. Sed porta, eros vitae malesuada dictum, sapien lacus volutpat tortor, ut commodo tellus risus ac leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus tellus vel tristique posuere. Cras suscipit feugiat felis quis tristique. Integer in lobortis purus, a volutpat nulla. Etiam cursus rhoncus felis at placerat. Aenean lectus mi, vulputate eget facilisis molestie, molestie id augue. Nunc lacus ligula, ultricies vitae tincidunt non, tincidunt sed turpis. Phasellus pharetra id ante rhoncus faucibus. Cras rutrum quam lobortis nisl congue, sed vehicula turpis feugiat. Morbi vitae sagittis turpis. Nam mattis, tortor vel pharetra gravida, massa augue dapibus mi, eu aliquam mi libero euismod lectus. Sed condimentum mi ut ex dignissim porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras enim libero, lobortis ac purus semper, laoreet scelerisque odio.
    
    Etiam mattis dolor dui, id tempus eros ultricies vel. Cras ut felis sodales, tincidunt elit ut, dictum lorem. Sed quis augue nec massa pulvinar congue ac id tortor. Praesent consectetur at eros ac varius. Quisque congue diam ac nibh aliquam rhoncus. Sed eget ligula ex. Morbi eu purus feugiat, interdum libero condimentum, accumsan ligula. In rutrum magna justo, a accumsan nibh pulvinar nec. In quam ligula, vulputate molestie odio eget, efficitur laoreet ante. Aenean vel ornare ligula, vitae egestas dolor. Aliquam in massa vitae urna hendrerit venenatis. Nulla cursus molestie elementum. Vestibulum consequat sed sapien nec mattis. Nulla porta feugiat libero, at volutpat lacus lacinia et.
    
    Aenean massa justo, suscipit nec odio non, dignissim iaculis velit. Cras ornare luctus tortor ut convallis. Vestibulum porta convallis urna, sed luctus justo auctor vel. Donec quis orci ut arcu semper aliquet. Fusce viverra purus sed malesuada imperdiet. Donec id nulla ipsum. Curabitur condimentum efficitur eros ac eleifend. Vestibulum bibendum euismod urna. Morbi imperdiet eu magna dignissim posuere. Nullam eget nulla sodales, sagittis leo sit amet, ornare felis. Sed sit amet eleifend velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus auctor facilisis enim, pulvinar lacinia leo blandit sed. Nulla non est sed lacus aliquet posuere vel nec quam.
    
    Sed iaculis aliquet pharetra. Nulla eget lectus at dolor fermentum placerat. Etiam at feugiat ipsum. Duis aliquet ligula nec luctus ornare. Praesent sagittis arcu et risus gravida sagittis. Nulla ex sem, convallis eget luctus sed, tempus eget sapien. Sed vitae laoreet metus. Cras quis lobortis ipsum, sit amet bibendum erat. Nulla fermentum consequat enim eu congue. Suspendisse at ultricies nunc, at condimentum neque. Sed vulputate id velit sit amet commodo. Suspendisse potenti.
    
    In tempor ante ac velit vulputate consequat. Donec a nunc gravida, lacinia erat eu, venenatis ipsum. In finibus mauris in quam tristique, in ornare leo molestie. Etiam in tortor egestas, varius ipsum vel, consectetur nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer fermentum justo id elit pellentesque vestibulum. Aenean auctor venenatis neque, at pellentesque neque convallis convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et odio posuere, vehicula enim a, euismod elit. Ut luctus id turpis in pellentesque.
    
    Etiam nec viverra leo. Integer vestibulum pulvinar tempor. Vestibulum consequat orci odio. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc ullamcorper eu nisl laoreet luctus. Nunc aliquam ante eget dolor viverra, sed eleifend felis tristique. Suspendisse convallis leo sit amet massa luctus, et tempus mi sagittis. Aliquam eget augue a turpis imperdiet mattis id vel metus.
    
    Cras fermentum, nisl lacinia rhoncus suscipit, magna nibh vulputate lorem, vel vehicula orci lacus quis nisi. Aliquam erat volutpat. Sed id urna ac velit commodo commodo ut ut tellus. Nullam a consectetur nulla. Vestibulum a dui tellus. Duis ultrices elementum enim sed feugiat. Vivamus justo libero, luctus ut erat eget, dictum pulvinar odio. Nulla interdum enim turpis. Aliquam porta rhoncus libero, nec imperdiet felis porta id. Curabitur congue ultrices lacinia.
    
    Etiam non accumsan ex. Ut commodo elit eget convallis finibus. Phasellus gravida metus vitae risus euismod accumsan. Praesent nunc tellus, sodales eu vulputate vitae, consectetur a leo. Aenean ullamcorper, nunc non posuere porttitor, risus lorem feugiat neque, in posuere turpis nulla vel lorem. Duis eget laoreet nisi, vitae egestas odio. Nam dignissim, lectus ut blandit dapibus, tortor erat aliquam nisi, sed viverra nulla lectus rutrum leo. Pellentesque tincidunt rhoncus ipsum id feugiat.`}
      </div>
    </div>
  );
};
